metadata:
  favicon: ''
  title: Family Budget Manager
  description: ''
  breakpoints: []
  rendererCachingEnabled: true
  skipDepsComparisonInCompilerCache: false
  vibeAppPhase: impl
  vibeAppAutoApplyMigrations: true
  vibeAppConnectedDatasources: []
  chatId: '93282'
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
  density: compact
  hideRenderCachingSettings: false
internalType: vibe_project
id: saLM0aqNYi
